### ISSUE TITLE
[FEATURE]부서 소개 섹션 추가

### ISSUE THREAD

**Issue by imratatouille** [hansei-hanum/recruit.hanum.us#4]
## 💣 기능 설명
**어떤 기능을 개발하실 건가요? 간단하게 작성해주세요!**
부서 소개 섹션을 추가합니다

## 🔨 테스크
**기능이 개발되기까지 필요한 테스크를 작성해주세요.**
- [x] 부서 소개 섹션 만들기

## 🎸 기타
**해당 이슈에서 참고할 사항이나 그 외 필요한 내용을 작성해주세요.**

**Comment by imratatouille** [comment]
figma에서 미쳐 확인하지 못했던 모바일 웹 프론트 부분을 고치겠습니다

**Comment by choi138** [comment]
> figma에서 미쳐 확인하지 못했던 모바일 웹 프론트 부분을 고치겠습니다

아냐아냐 괜찮아 안고쳐도 돼

**Comment by choi138** [comment]
지금 앱이랑 웹이랑 아예 레포 다르게 하려고 해서 괜찮아 
만드느라 수고했어

**Comment by imratatouille** [comment]
정말 죄송합니다 figma가 처음이라 미쳐 다 확인하지 못했습니다
다음부터는 조심하겠습니다
